---
title: Nangka
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    permalink: "/blog/:title"
description: Welcome to my awesome blog..
author: rmsubekti
author_avatar: assets/avatar.png
email: su@bekti.net
baseurl: "/nangka"
url: ''
github_username: rmsubekti/nangka
google_analytics: UA-124XXXXX-XX
google_site_verification: McHopQXXXXQKRCXXXXX3XXXOXXXX
cse_id: 010xxxxxxx00xxxxxxxx:v_uiprmpwme
logo: "/assets/icons/512.png"
social:
  name: Nangka
  links:
  - https://twitter.com/rmsubekti
  - https://www.facebook.com/rmsbekti
  - https://www.linkedin.com/in/rahmatsubekti
  - https://plus.google.com/u/0/+rmsubekti
  - https://github.com/rmsubekti
  - https://mozillians.org/u/bekti/
  - https://developer.mozilla.org/id/profiles/bekti
sass:
  style: compressed
markdown: kramdown
kramdown:
  parse_block_html: true
remote_theme: rmsubekti/nangka
include:
- _pages
paginate: 10
paginate_path: "/blog/:num/"
