---
title: Makcimka Bro
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:name/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Branding & Digital design
url: https://makcimkabro.github.io
baseurl: ''
author:
  name: Ваше имя
  email: your-email@example.com
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title/"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
include:
- _assets
exclude:
- node_modules/
- package.json
- package-lock.json
- tailwind.config.js
- postcss.config.js
- README.md
- Gemfile
- Gemfile.lock
- vendor/
sass:
  sass_dir: _sass
  style: compressed
